from graph import Graph

graph = Graph()
graph.add_vertex('A', 'B', 'C', 'D', 'E')
graph.add_edge('A', 'B')
graph.add_edge('A', 'D')
graph.add_edge('B', 'C')
graph.add_edge('B', 'D')
graph.add_edge('B', 'E')
graph.add_edge('D', 'E')
print(graph)
print("Adjazenzmatrix:")
print(graph.adjacency_matrix)
print("Von A ausgehende Kanten:")
print(graph.edges_from_vertex('A'))
print("Nachbarknoten von A:")
print(graph.neighbors('A'))
graph.visualize()
print("Entferne Knoten D")
graph.remove_vertex('D')
print(graph)
print("Adjazenzmatrix:")
print(graph.adjacency_matrix)
print("Von A ausgehende Kanten:")
print(graph.edges_from_vertex('A'))
print("Nachbarknoten von A:")
print(graph.neighbors('A'))
graph.visualize()

